# Generated by Django 5.0.4 on 2024-04-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0004_auto_20210331_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='rank',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
